export const SCROLL_ADD = "SCROLL_ADD";
export const SCROLL_ADD_START = "SCROLL_ADD_START";
export const SCROLL_ADD_SUCCESS = "SCROLL_ADD_SUCCESS";
export const SCROLL_FETCH_FAIL = "SCROLL_FETCH_FAILED";
export const SCROLL_INIT = "SCROLL_INIT";
export const SCROLL_SET = "SCROLL_SET";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
